// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    afterBtnWrapper: string
    category: string
    contentWrapper: string
    heading: string
    nothingHereYet: string
    opacityIn: string
    opacityInDelayed: string
    popIn: string
    slideInBottomWithOpacity: string
    slideInRight50perc: string
    slideInTop: string
}
export const cssExports: CssExports
export default cssExports
