// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    actions: string
    headerMobile: string
    headerMobileBtn: string
    logo: string
    mobileLogo: string
    opacityIn: string
    opacityInDelayed: string
    popIn: string
    slideInBottomWithOpacity: string
    slideInTop: string
}
export const cssExports: CssExports
export default cssExports
