// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    link: string
    opacityIn: string
    opacityInDelayed: string
    popIn: string
    slideInBottomWithOpacity: string
    slideInRight: string
    slideInTop: string
    translateYArrowsMobile: string
    translateYTextMobile: string
}
export const cssExports: CssExports
export default cssExports
