// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    opacityIn: string
    opacityInDelayed: string
    popIn: string
    slideInBottomWithOpacity: string
    slideInTop: string
    slider: string
    sliderWrapper: string
}
export const cssExports: CssExports
export default cssExports
