// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    mainNavCat: string
    opacityIn: string
    opacityInDelayed: string
    popIn: string
    slideInBottomWithOpacity: string
    slideInTop: string
}
export const cssExports: CssExports
export default cssExports
