// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    category: string
    heading: string
    sideMenuWrapper: string
}
export const cssExports: CssExports
export default cssExports
