// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    changeBoxShadow: string
    changeBoxShadowContainer: string
    container: string
    opacityIn: string
    opacityInDelayed: string
    popIn: string
    slideInBottom: string
    slideInBottomWithOpacity: string
    slideInRight: string
    slideInTop: string
    wrapper: string
}
export const cssExports: CssExports
export default cssExports
