// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    header: string
    loginBtn: string
    logoutBtn: string
    opacityIn: string
    popIn: string
    slideInBottomWithOpacity: string
    slideInRight: string
    slideInTop: string
}
export const cssExports: CssExports
export default cssExports
