// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    button: string
    lisItemCard: string
    opacityIn: string
    popIn: string
    price: string
    quantity: string
    shopName: string
    slideInBottomWithOpacity: string
    slideInRight: string
    slideInTop: string
    title: string
}
export const cssExports: CssExports
export default cssExports
