// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    contentPageLayout: string
    contentWrapper: string
}
export const cssExports: CssExports
export default cssExports
